# Python Numpy

In [1]:
import numpy as np

# One Dimensional Array 

In [2]:
arr = np.array([1,2,3],dtype='f')

In [3]:
arr

array([1., 2., 3.], dtype=float32)

In [4]:
arr[2]

3.0

In [5]:
arr.dtype

dtype('float32')

In [44]:
arr.ndim

1

# Two Dimesional Array

In [7]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**dtype**: Return the data type of the array.

In [9]:
myarr.dtype

dtype('int32')

**size**: Return the total number of elements in the array.

In [10]:
myarr.size

9

In [11]:
myarr[1,1]

5

**shape**: Return a tuple of rows and columns.

In [12]:
myarr.shape

(3, 3)

In [13]:
myarr.argmax()

8

**armax()**:Return the index of the highest integer.

**argmin()**:Return the index of the lowest integer.

In [14]:
myarr.argmin()

0

**max()**: Return the maximum number in the array.

In [15]:
myarr.max()

9

**min()**: Return the minimum number in the array.

In [16]:
myarr.min()

1

**reshape()**: Reshape the origional list,e.g: columns and rows.

In [17]:
myarr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Adding Two Arrays**: You can add two arrays in numpy unlike list of python which concatenate the list.

In [35]:
a1 = np.array([1,2,3])

In [36]:
a2 = np.array([4,5,6])

In [37]:
a1 + a2

array([5, 7, 9])

In [38]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Views and Copy

**Copy**: Return a copy no changing will be made if the origional file change and vice versa.


**View**:If changes occur in the origional file or vice versa then changes will be occured in the view also.

In [55]:
ar = np.array([1,2,3])
c = ar.copy()
ar[0] = 10
print(ar)
print(c)

[10  2  3]
[1 2 3]


In [57]:
ar = np.array([1,2,3])
v = ar.view()
ar[0] = 10
v[1] = 20
print(ar)
print(v)

[10 20  3]
[10 20  3]


In [59]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**T**: Reverse the rows and columns.

In [60]:
myarr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Looping through the array**

In [64]:
one_dim = np.array([1,2,3])
for i in one_dim:
    print(i)

1
2
3


In [67]:
two_dim = np.array([[1,2,3],[4,5,6]])
for i in two_dim:
#     print(i)
    for j in i:
        print(j)

1
2
3
4
5
6


**--> You can also return a specific elements from the array based on some condition**

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[arr>5]

array([6, 7, 8, 9])

In [6]:
arr[arr == 7]

array([7])